#!/bin/bash
# ============================================================================
# NaoKernel Run Script
# Launches the kernel in QEMU
# ============================================================================

set -e  # Exit on error

# Load library
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib.sh"

# Resolve a working Python interpreter
detect_python() {
    if command_exists python3; then
        echo "python3"
    elif command_exists python; then
        echo "python"
    else
        log_error "Python is required to generate drive images (python3 or python not found)"
        exit 1
    fi
}

# Generate drive images via disk.py and stage them in run/
prepare_drives() {
    log_step "Generating drive images via disk.py..."

    PY_BIN=$(detect_python)

    # Use a temp workspace to avoid polluting the repo root
    TMP_DIR=$(mktemp -d 2>/dev/null || mktemp -d -t naokernel_disk)
    log_info "Using temp dir: $TMP_DIR"

    # Generate disk.sh and disk.dir (5 HDDs + 2 FDDs by default)
    (cd "$TMP_DIR" && "$PY_BIN" "$SCRIPT_DIR/disk.py" \
        10MBD 10MBD 8MBD 6MBD 3MBD \
        2MBF 10MBF)

    log_info "Run the following command to generate disk.sh: $PY_BIN $SCRIPT_DIR/disk.py 10MBD 10MBD 8MBD 6MBD 3MBD 2MBF 10MBF"

    # Run the generated script to create the images
    (cd "$TMP_DIR" && bash disk.sh)

    # Stage into run/
    rm -rf run
    mkdir -p run
    cp "$TMP_DIR"/*.img run/
    cp "$TMP_DIR"/disk.dir run/

    log_success "Drive images prepared in run/"
    rm -rf "$TMP_DIR"
}

# ============================================================================
# Run Functions
# ============================================================================

run_kernel() {
    log_step "Starting NaoKernel in QEMU..."
    
    # Check if kernel binary exists
    if [[ ! -f "bin/kernel" ]]; then
        log_error "Kernel binary not found at bin/kernel"
        log_error "Please build the kernel first with: ./start.sh --build"
        exit 1
    fi
    
    # Ensure drive images exist; generate if missing
    if [[ ! -f "run/disk.dir" ]]; then
        prepare_drives
    fi

    log_info "Preparing QEMU command-line arguments..."
    
    # Build QEMU command as an array for safe quoting
    local -a qemu_cmd=(qemu-system-i386 -kernel bin/kernel -m 512M)
    local hd_index=0 fd_index=0
    local hd_letters=(a b c d)
    local fd_letters=(a b)
    
    # read loop under set -e: append '|| true' to avoid EOF causing exit
    while IFS=' ' read -r drive_file size drive_type; do
        # Skip empty lines and comments
        [[ -z "$drive_file" ]] || [[ "$drive_file" =~ ^# ]] && continue

        # Trim whitespace and stray CRs
        drive_file=$(echo "${drive_file%%$'\r'}" | xargs)
        drive_type=$(echo "${drive_type%%$'\r'}" | xargs)

        if [[ ! -f "run/$drive_file" ]]; then
            log_warning "Drive file not found: run/$drive_file"
            continue
        fi

        if [[ "$drive_type" == "D" ]]; then
            if (( hd_index < ${#hd_letters[@]} )); then
                local letter=${hd_letters[$hd_index]}
                qemu_cmd+=("-drive" "file=run/$drive_file,format=raw,if=ide,index=$hd_index")
                log_info "Attaching HDD $letter (ide index $hd_index): run/$drive_file"
            else
                log_warning "IDE supports only 4 HDD slots (hda-hdd). Skipping run/$drive_file"
            fi
            ((hd_index++))
        elif [[ "$drive_type" == "F" ]]; then
            if (( fd_index < ${#fd_letters[@]} )); then
                local letter=${fd_letters[$fd_index]}
                qemu_cmd+=("-drive" "file=run/$drive_file,format=raw,if=floppy,index=$fd_index")
                log_info "Attaching FDD $letter: run/$drive_file"
            else
                log_warning "PC floppy controller supports only 2 drives (fda-fdb). Skipping run/$drive_file"
            fi
            ((fd_index++))
        else
            log_warning "Unknown drive type: $drive_type"
        fi
    done < run/disk.dir || true
    
    log_info "Launching QEMU with kernel and drives..."
    log_info "Command: ${qemu_cmd[*]}"
    log_info ""
    
    "${qemu_cmd[@]}"
}

# ============================================================================
# Main Execution
# ============================================================================

main() {
    log_info "================================================"
    log_info "NaoKernel Execution"
    log_info "================================================"
    log_info ""

    # Check if QEMU is installed
    if ! command_exists qemu-system-i386; then
        log_error "qemu-system-i386 not found"
        log_error "Please install QEMU first"
        exit 1
    fi

    # Ensure drive images exist (generated by disk.py)
    if [[ ! -f "run/disk.dir" ]]; then
        prepare_drives
    fi
    
    run_kernel
}

main "$@"
